
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projed9469e53a99d7f7f46176906582f04423619183.EntityFramework.FunctionalTests.TestModels.TemplateModels.CsAdvancedPatterns
{

using System;
    using System.Collections.Generic;
    
public partial class OfficeMf
{

    public OfficeMf()
    {

        this.WhiteBoards = new HashSet<WhiteboardMf>();

    }


    public string Number { get; set; }

    public System.Guid BuildingId { get; set; }

    internal string Description { get; private set; }



    private BuildingMf Building { get; set; }

    public virtual ICollection<WhiteboardMf> WhiteBoards { internal get; set; }

}

}
