
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj8d452499b23e250232406fa9c875973a054b17f9.FunctionalTests.TestModels.TemplateModels.CsAdvancedPatterns
{

using System;
    
internal partial class SiteInfoMf
{

    protected Nullable<int> Zone { get; private set; }

    public string Environment { get; set; }

}

}
