
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj8b9180bea7178d8348de47e28237c05ddb8a8244.EntityFramework.VBTests.VbMonsterModel


Partial Public Class ContactDetailsMm

    Public Property Email As String



    Public Property HomePhone As Another.Place.PhoneMm = New Another.Place.PhoneMm

    Public Property WorkPhone As Another.Place.PhoneMm = New Another.Place.PhoneMm

    Public Property MobilePhone As Another.Place.PhoneMm = New Another.Place.PhoneMm


End Class



End Namespace
