
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj8b9180bea7178d8348de47e28237c05ddb8a8244.EntityFramework.VBTests.VbMonsterModel


Partial Public Class LastLoginMm

    Public Property Username As String

    Public Property LoggedIn As Date

    Public Property LoggedOut As Nullable(Of Date)



    Public Overridable Property Login As Another.Place.LoginMm


End Class



End Namespace
