
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj8b9180bea7178d8348de47e28237c05ddb8a8244.EntityFramework.VBTests.VbMonsterModel


Partial Public Class MessageMm

    Public Property MessageId As Integer

    Public Property FromUsername As String

    Public Property ToUsername As String

    Public Property Sent As Date

    Public Property Subject As String

    Public Property Body As String

    Public Property IsRead As Boolean



    Public Overridable Property Sender As Another.Place.LoginMm

    Public Overridable Property Recipient As Another.Place.LoginMm


End Class



End Namespace
