
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.VBTests.VbMonsterModel


Partial Public Class ContactDetailsMm

    Public Property Email As String



    Public Property HomePhone As Another.Place.PhoneMm = New Another.Place.PhoneMm

    Public Property WorkPhone As Another.Place.PhoneMm = New Another.Place.PhoneMm

    Public Property MobilePhone As Another.Place.PhoneMm = New Another.Place.PhoneMm


End Class



End Namespace
