
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.VBTests.VbMonsterModel


Partial Public Class DiscontinuedProductMm
             Inherits ProductMm

    Public Property Discontinued As Date

    Public Property ReplacementProductId As Nullable(Of Integer)



    Public Overridable Property ReplacedBy As ProductMm


End Class



End Namespace
