
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.VBTests.VbMonsterModel


Partial Public Class IncorrectScanMm

    Public Property IncorrectScanId As Integer

    Public Property ExpectedCode As Byte()

    Public Property ActualCode As Byte()

    Public Property ScanDate As Date

    Public Property Details As String



    Public Overridable Property ExpectedBarcode As BarcodeMm

    Public Overridable Property ActualBarcode As BarcodeMm


End Class



End Namespace
