
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.VBTests.VbMonsterModel


Partial Public Class ProductReviewMm

    Public Property ProductId As Integer

    Public Property ReviewId As Integer

    Public Property Review As String



    Public Overridable Property Product As ProductMm

    Public Overridable Property Features As ICollection(Of ProductWebFeatureMm) = New HashSet(Of ProductWebFeatureMm)


End Class



End Namespace
