
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.VBTests.VbMonsterModel


Partial Public Class SmartCardMm

    Public Property Username As String

    Public Property CardSerial As String

    Public Property Issued As Date



    Public Overridable Property Login As Another.Place.LoginMm

    Public Overridable Property LastLogin As LastLoginMm


End Class



End Namespace
