
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj1571862b0479b8f1e1976abceac0bca9f3cdd2d7.TestModels.TemplateModels.CsAdvancedPatterns
{

using System;
    using System.Collections.Generic;
    
internal partial class MailRoomMf
{

    public int id { get; set; }

    public System.Guid BuildingId { get; set; }



    public virtual BuildingMf Building { get; set; }

}

}
