
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj1571862b0479b8f1e1976abceac0bca9f3cdd2d7.TestModels.TemplateModels.CsAdvancedPatterns
{

using System;
    using System.Collections.Generic;
    
public partial class WorkOrderMf
{

    public int WorkOrderId { get; set; }

    public int EmployeeId { get; set; }

    public string Details { get; set; }



    internal virtual EmployeeMf Employee { get; set; }

}

}
