
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Projed9469e53a99d7f7f46176906582f04423619183.EntityFramework.VBTests.VbMonsterModel


Partial Public Class PasswordResetMm

    Public Property ResetNo As Integer

    Public Property Username As String

    Public Property TempPassword As String

    Public Property EmailedTo As String



    Public Overridable Property Login As Another.Place.LoginMm


End Class



End Namespace
