
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.FunctionalTests.TestModels.TemplateModels.CsMonsterModel
{

using System;
    using System.Collections.Generic;
    
public partial class IncorrectScanMm
{

    public int IncorrectScanId { get; set; }

    public byte[] ExpectedCode { get; set; }

    public byte[] ActualCode { get; set; }

    public System.DateTime ScanDate { get; set; }

    public string Details { get; set; }



    public virtual BarcodeMm ExpectedBarcode { get; set; }

    public virtual BarcodeMm ActualBarcode { get; set; }

}

}
