
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.FunctionalTests.TestModels.TemplateModels.CsMonsterModel
{

using System;
    using System.Collections.Generic;
    
public partial class SupplierMm
{

    public SupplierMm()
    {

        this.Products = new HashSet<ProductMm>();

        this.BackOrderLines = new HashSet<BackOrderLineMm>();

    }


    public int SupplierId { get; set; }

    public string Name { get; set; }



    public virtual ICollection<ProductMm> Products { get; set; }

    public virtual ICollection<BackOrderLineMm> BackOrderLines { get; set; }

    public virtual SupplierLogoMm Logo { get; set; }

}

}
