
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj326d525b1d7d8e1c95f7227be63238ec783a9e92.EntityFramework.FunctionalTests.TestModels.TemplateModels.CsAdvancedPatterns
{

using System;
    using System.Collections.Generic;
    
internal partial class MailRoomMf
{

    public int id { get; set; }

    public System.Guid BuildingId { get; set; }



    public virtual BuildingMf Building { get; set; }

}

}
