//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG.IntelliExtract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPG.IntelliExtract.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found on project: .
        /// </summary>
        internal static string IntelliExtractPackage__CreateProjectionBuffer_Document_not_found_on_project__ {
            get {
                return ResourceManager.GetString("IntelliExtractPackage__CreateProjectionBuffer_Document_not_found_on_project__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text view is currently open.
        /// </summary>
        internal static string IntelliExtractPackage_NotifyHilightChanged_No_text_view_is_currently_open {
            get {
                return ResourceManager.GetString("IntelliExtractPackage_NotifyHilightChanged_No_text_view_is_currently_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string IntelliExtractPackage_NotifyLocationsSelected_ {
            get {
                return ResourceManager.GetString("IntelliExtractPackage_NotifyLocationsSelected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class: .
        /// </summary>
        internal static string IntelliExtractPackage_NotifyLocationsSelected_class__ {
            get {
                return ResourceManager.GetString("IntelliExtractPackage_NotifyLocationsSelected_class__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to inform negative locations?.
        /// </summary>
        internal static string IntelliExtractPackage_NotifyLocationsSelected_Do_you_want_to_inform_negative_locations_ {
            get {
                return ResourceManager.GetString("IntelliExtractPackage_NotifyLocationsSelected_Do_you_want_to_inform_negative_loca" +
                        "tions_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string IntelliExtractPackage_NotifyLocationsSelected_Done_ {
            get {
                return ResourceManager.GetString("IntelliExtractPackage_NotifyLocationsSelected_Done_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a correct location?.
        /// </summary>
        internal static string IntelliExtractPackage_NotifyLocationsSelected_Is_it_a_correct_location_ {
            get {
                return ResourceManager.GetString("IntelliExtractPackage_NotifyLocationsSelected_Is_it_a_correct_location_", resourceCulture);
            }
        }
    }
}
