
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projed9469e53a99d7f7f46176906582f04423619183.EntityFramework.FunctionalTests.TestModels.TemplateModels.CsMonsterModel
{

using System;
    
public partial class DimensionsMm
{

    public decimal Width { get; set; }

    public decimal Height { get; set; }

    public decimal Depth { get; set; }

}

}
