
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj1571862b0479b8f1e1976abceac0bca9f3cdd2d7.TestModels.TemplateModels.CsMonsterModel
{

using System;
    using System.Collections.Generic;
    
public partial class ComputerMm
{

    public int ComputerId { get; set; }

    public string Name { get; set; }



    public virtual ComputerDetailMm ComputerDetail { get; set; }

}

}
