
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj8d452499b23e250232406fa9c875973a054b17f9.FunctionalTests.TestModels.TemplateModels.CsMonsterModel
{

using System;
    using System.Collections.Generic;
    
public partial class BackOrderLineMm : OrderLineMm
{

    public System.DateTime ETA { get; set; }



    public virtual SupplierMm Supplier { get; set; }

}

}
