
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Namespace Proj829dec5d15c3d930815d72ce2d6909c51a97b1ef.EntityFramework.VBTests.VbAdvancedPatterns


Partial Public Class WhiteboardMf

    Public Property iD As Byte()

    Public Property AssetTag As String



    Public Overridable Property Office As OfficeMf


End Class


End Namespace
