
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic



Namespace Proj829dec5d15c3d930815d72ce2d6909c51a97b1ef.EntityFramework.VBTests.VbMonsterModel


Partial Public Class LicenseMm

    Public Property Name As String

    Public Property LicenseNumber As String

    Public Property LicenseClass As String = "C"

    Public Property Restrictions As String

    Public Property ExpirationDate As Date

    Public Property State As Nullable(Of Another.Place.LicenseStateMm)



    Public Overridable Property Driver As DriverMm


End Class



End Namespace
