
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proj829dec5d15c3d930815d72ce2d6909c51a97b1ef.EntityFramework.FunctionalTests.TestModels.TemplateModels.CsAdvancedPatterns
{

using System;
    using System.Collections.Generic;
    
public partial class WorkOrderMf
{

    public int WorkOrderId { get; set; }

    public int EmployeeId { get; set; }

    public string Details { get; set; }



    internal virtual EmployeeMf Employee { get; set; }

}

}
