
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Namespace Projed9469e53a99d7f7f46176906582f04423619183.EntityFramework.VBTests.VbAdvancedPatterns


Partial Friend Class SiteInfoMf


        Private _Zone As Nullable(Of Integer)
        Protected Property Zone As Nullable(Of Integer)
            Get
                Return _Zone
            End Get
            Private Set(ByVal value As Nullable(Of Integer))
                _Zone = value
            End Set
        End Property

    Public Property Environment As String


End Class


End Namespace
